mosip/mosip-helm

- charts/activemq-artemis/templates/istio-vs-gateway.yaml
- charts/activemq-artemis/templates/service.yaml
- charts/activemq-artemis/values.yaml
A quick documentation and helm chart update for activemq-artemis
> [MOSIP-13871] Slight Changes to activemq-artemis helm chart

- charts/keycloak-init/values.yaml
Updated client roles & mappers
> [ MOSIP-20485 ] updated keycloak-init chart

- charts/postgres-init/templates/pms-env-configmap.yaml
- charts/postgres-init/values.yaml
> [ MOSIP-20846 ] Updated postgres-init docker image & added new env var

- charts/admin-ui/templates/configmap.yaml
added new attribute templateRepoUrl
>  [ DSD-960 ] updated admin-ui configmap.yaml

- charts/mock-abis/templates/virtualservice.yaml
- charts/mock-abis/values.yaml
> [ DSD-987 ] Added virtualservice on mock-abis to enable access to 

- charts/config-server/templates/_overides.tpl
- charts/config-server/templates/secrets_various.yaml
> [ DSD-1058 ] updated config-server helm/charts

- .github/workflows/push_trigger.yaml
> Revert "[ MOSIP-21108 ] updated push_trigger.yaml to publish only required helm/charts"

- charts/config-server/.helmignore
- charts/config-server/README.md
Documented steps to add new placeholder
> [ MOSIP-20556 ] added README.md

- charts/mosip-file-server/templates/configmaps.yaml
- charts/mosip-file-server/values.yaml
publicKeyPem was empty due to // in request urls
> [ MOSIP-22839 ] fixed auth_url_env & key_url_env url issue

- charts/apitestrig/templates/cronjob-rollout-restart.yaml
- charts/apitestrig/values.yaml
increased cpu to 500m, memory to 3.5GiB, & JAVA_OPTS to 3.5GiB
> [ MOSIP-23217 ] updated apitestrig helm/chart

- charts/ida-internal/templates/servicemonitor.yaml
- charts/idgenerator/templates/servicemonitor.yaml
- charts/partner-onboarder/templates/servicemonitor.yaml
Update service monitor port to match service port
> Update on servicemonitor.yaml

- charts/mosip-file-server/Chart.lock
- charts/mosip-file-server/templates/configmaps.yaml
- charts/mosip-file-server/templates/deployment.yaml
- charts/mosip-file-server/templates/gateway.yaml
- charts/mosip-file-server/templates/virtualservice.yaml
- charts/mosip-file-server/values.yaml
Provided mobile app download links
> [DSD-1341]cherry picked the commit from develop [d932b203d21104e38066c31cf7b027f0d5c61d11] to 1.2.0.1 updated the mosip-file-server helm/charts 

- charts/config-server/templates/_overides.tpl
- charts/landing-page/templates/configmap-index.yaml
- charts/landing-page/values.yaml
- charts/mock-smtp/templates/gateway.yaml
- charts/mock-smtp/templates/virtualservice.yaml
- charts/mock-smtp/values.yaml
config-server,
landing-page,
mock-smtp
> [ MOSIP-24038 ] updated below charts for mock-smtp

- .github/chart-schema.yaml
- .github/chart-testing-config.yaml
- .github/chart_schema.yaml
- .github/ct.yml
- .github/health-check-schema.yaml
- .github/lintconf.yaml
- .github/workflows/helm-lint-manual.yaml
- .github/workflows/helm-lint.yaml
- README.md
* To check helm chart linting
* To check health check for deployment / statefulset yamls
> [ MOSIP-24334 ] Added workflows for the following

- .github/workflows/helm-lint-manual.yaml
- .github/workflows/helm-lint.yaml
* ls return non-zero exit code
> [ DSD-1623 ] updated helm-lint workflows to fix the following

- .github/workflows/helm-lint-manual.yaml
- .github/workflows/helm-lint.yaml
* print line number starting with ---
> [ DSD-1630 ] updated helm-lint workflows to fix the following

- .github/health-check-schema.yaml
- .github/workflows/helm-lint-manual.yaml
- .github/workflows/helm-lint.yaml
- .github/workflows/push_trigger.yaml
- .gitignore
* for specific charts
* run chart linting for all charts
> [ DSD-1683 ] Added a feature to ignore chart linting

- .github/workflows/helm-lint-manual.yaml
- .github/workflows/helm-lint.yaml
- .gitignore
- charts/activemq-artemis/templates/master-statefulset.yaml
- charts/activemq-artemis/templates/slave-statefulset.yaml
…tiveMQ chart to ignore_chart list for develop branch
> [DSD-1766] Removed startupProbe from ActiveMQ helm chart and added ActiveMQ chart to ignore_chart list for develop branch

- charts/conf-secrets/templates/secret.yaml
- charts/conf-secrets/values.yaml
- charts/config-server/templates/_overides.tpl
* mosip-ida-kyc-token-secret
* mosip-partner-crypto-p12-password
> [ DSD-1944 ] added new placeholder for config-server

- charts/apitestrig/Chart.yaml
- charts/apitestrig/templates/configmaps.yaml
- charts/apitestrig/templates/secrets.yaml
- charts/apitestrig/values.yaml
* Added flag to run api-testrig for insecure self-signed servers
* Restructured apitestrig helm chart and deployment scripts
> [ MOSIP-25254 ] updated apitestrig helm chart to run apitestrig for self-signed env

- charts/keycloak-init/values.yaml
add client scopes to pms client
> [ MOSIP-25253 ] updated keycloak-init chart

- charts/postgres-init/Chart.yaml
- charts/postgres-init/templates/esignet-env-configmap.yaml
- charts/postgres-init/templates/esignet-job.yaml
- charts/postgres-init/templates/mockidentitysystem-env-configmap.yaml
- charts/postgres-init/templates/mockidentitysystem-job.yaml
- charts/postgres-init/values.yaml
> [ DSD-2389 ] Updated postgres-init helm chart

- charts/authdemo/values.yaml
- charts/dslorchestrator/values.yaml
- charts/packetcreator/values.yaml
[ DSD-2454 ] updated dslrig configmap
> [ DSD-2545 ] updated docker images

- charts/apitestrig/values.yaml
- charts/landing-page/templates/configmap-index.yaml
changed from idp to esignet in landing page chart file
> DSD-2547 Renamed IDP to esignet

- charts/conf-secrets/templates/secret.yaml
- charts/config-server/templates/_overides.tpl
> Revert "MOSIP-26730 randomly generate 6 byte secret for mimoto"

- charts/activemq-artemis/templates/virtualservice.yaml
> [DSD-2730] Enabled "ws" endpoint for port "61616" for activemq

- charts/keycloak-init/values.yaml
> Revert "[DSD-3307]Added new role"

- charts/mosip-file-server/Chart.yaml
> [MOSIP-29616]Updated Charts mosip-file-server 1.2.0.1

- charts/partner-onboarder/templates/jobs.yaml
- charts/partner-onboarder/templates/role.yaml
- charts/partner-onboarder/templates/rolebinding.yaml
- charts/partner-onboarder/values.yaml
> [DSD-3884] Updated onboarder helm chart esignet vc release

- charts/apitestrig/templates/_helpers.tpl
- charts/apitestrig/templates/cluster-role.yaml
- charts/apitestrig/templates/clusterrolebinding.yaml
- charts/apitestrig/templates/cronjob.yaml
- charts/apitestrig/values.yaml
- charts/databreachdetector/templates/cronjob.yaml
- charts/dslorchestrator/templates/_helpers.tpl
- charts/dslorchestrator/templates/cluster-role.yaml
- charts/dslorchestrator/templates/clusterrolebinding.yaml
- charts/dslorchestrator/templates/cronjob.yaml
- charts/dslorchestrator/values.yaml
- charts/packetcreator/templates/_helpers.tpl
- charts/packetcreator/templates/deployment.yaml
- charts/packetcreator/templates/role.yaml
- charts/packetcreator/templates/rolebinding.yaml
- charts/uitestrig/templates/_helpers.tpl
- charts/uitestrig/templates/cluster-role.yaml
- charts/uitestrig/templates/clusterrolebinding.yaml
- charts/uitestrig/templates/cronjob.yaml
- charts/uitestrig/values.yaml
Provided k8s role to fetch pods details
> [MOSIP-31031] Updated testrig charts to fetch docker hash IDs

- charts/apitestrig/values.yaml
> [DSD-4730] Added slack webhook URL to notify server end issues on your slack channel

- charts/landing-page/collab-index.html
[Resp. Screen Record](https://github.com/user-attachments/assets/535a6046-85af-4ab5-8da6-3fa62ece9e22)
> MOSIP-41235: Aligned the Icons, Implemented Dropdown inside Hamburger options.
